SHELL := /bin/sh
all-doc:
	@/bin/echo -ne "Creating \033[32mweaver.pdf\033[m.........."
	#magitex-cweb cweb/weaver.w
	magitex-cweb weaver_program.tex
	rm -f *.scn *.idx
	#dvipdf weaver.dvi
	dvipdf weaver_program.dvi
	rm -f *.aux *.toc *.idx *.ind *.ilg *.dvi
	@echo "OK"
