SHELL := /bin/sh
all-doc:
	@/bin/echo -ne "Creating \033[32mweaver.pdf\033[m.........."
	magitex-cweb cweb/weaver.w 
	rm -f *.scn *.idx
	dvipdf weaver.dvi
	rm -f *.aux *.tex *.toc *.idx *.ind *.ilg *.dvi
	@echo "OK"
