TANGLE=$(shell if which ctangle &> /dev/null; then echo "ctangle";\
	 else echo "notangle"; fi;)
CC=$(shell if which gcc &> /dev/null; then echo "gcc";\
	 else echo "clang"; fi;)
FLAGS=-Wall -O2 -g
OBJ=main.o memory.o weaver.o
LINK=-lm


main-prog:
	@echo -n "Compiling...................."
	@${TANGLE} cweb/weaver.w > .log || (/bin/echo -e "\033[31mFAILED\033[m" && cat .log && false)
	@rm weaver.c
	@${CC} ${FLAGS} src/weaver.c -o bin/weaver > /dev/null
	@echo "OK"
