EMCC=emcc

PROG=$(shell cat .weaver/name)
BC=$(shell for i in src/*.c; do echo $$(basename $${i%%.c}).bc; done)
W_BC=$(shell for i in src/weaver/*.c; do echo .weaver/$$(basename $${i%%.c}).bc; done)
HEADERS=$(shell echo src/*.h)
FLAGS=-Wall -O2
LIB=-lm -pthread
DEFINES=-DW_PROG=\"${PROG}\"

MAX_MEMORY=$(shell grep "^\#define[ \t]\+W_MAX_MEMORY[ \t]\+" conf/conf.h | grep -o "[0-9]\+")
WEB_MEMORY=$(shell grep "^\#define[ \t]\+W_WEB_MEMORY[ \t]\+" conf/conf.h | grep -o "[0-9]\+")
THREADED=$(shell grep "^\#define[ \t]\+W_MULTITHREAD" conf/conf.h)
ifeq ($(THREADED),)
THREAD_FLAG=
else
THREAD_FLAG=-s USE_PTHREADS=2
endif
FINAL_FLAGS=-s TOTAL_MEMORY=$$((${MAX_MEMORY}+${WEB_MEMORY})) ${THREAD_FLAG}

SOURCE_TEST=$(shell grep "^\#define[ \t]\+W_SOURCE[ \t]\+W_" conf/conf.h | grep -o "\(W_C\|W_CPP\)")
ifeq ($(strip $(SOURCE_TEST)),W_C)
FINAL_CC=${EMCC}
else ifeq ($(strip $(SOURCE_TEST)),W_CPP)
FINAL_CC=emcc++
else
err:
	$(error Invalid W_SOURCE in conf/conf.h)
endif


make-web: ${BC} ${W_BC} ${HEADERS} conf/conf.h
	mkdir -p web
	${FINAL_CC} ${DEFINES} ${BC} ${W_BC} ${FINAL_FLAGS} -o web/${PROG}.html ${LIB}
%.bc: src/%.c ${HEADERS}
	${EMCC} ${DEFINES} ${FLAGS} -c $< -o $$(basename $< .c).bc
.weaver/%.bc: src/weaver/%.c ${HEADERS}
	${EMCC} ${DEFINES} ${FLAGS} -c $< -o $(subst src/weaver/,.weaver/,$(subst .c,.bc,$<))
